dcConsData = [
	{name:"마법의소라고동.jpg",					keywords:["마법의소라고동"],				tags:["작품"],		soundURL:[
		"Sound/소라고동_가만.mp3",
		"Sound/소라고동_다시.mp3",
		"Sound/소라고동_안돼01.mp3",
		"Sound/소라고동_안돼02.mp3",
		"Sound/소라고동_돼01.mp3",
		"Sound/소라고동_돼02.mp3",
	]},	
	{name:"자피.png",							keywords:["자피?"],						tags:["자피"],		soundURL:"Sound/자피.mp3"},	
	{name:"아쉽다그치.png",							keywords:["아쉽다그치"],						tags:["림버스"],		soundURL:"Sound/asipda.mp3"},	
	{name:"clown.png",							keywords:["클보쑤,"클보수""],						tags:["동방"],
	{name:"자피아나.png",							keywords:["자피아나"],						tags:["자피"],		soundURL:"Sound/자피아나.mp3"},
	{name:"퀸암어퀸.gif",							keywords:["암어퀸"],						tags:["퀸","퀸동주"],		soundURL:"Sound/퀸암어퀸.mp3"},
	{name:"퀸살살해.gif",						keywords:["흐응살살해"],						tags:["퀸","퀸동주"],		soundURL:"Sound/퀸살살해.mp3"},
	{name:"퀸졸라껼.gif",							keywords:["졸라껼"],						tags:["퀸","퀸동주"],		soundURL:"Sound/퀸가슴졸라껼.mp3"},
	{name:"퀸졸라껼.gif",							keywords:["아잉씨","아잉쒸"],						tags:["퀸","퀸동주"],		soundURL:"Sound/퀸아잉씨.mp3"},
	{name:"퀸걸걸걸.gif",							keywords:["걸걸걸"],						tags:["퀸","퀸동주"],		soundURL:"Sound/퀸걸걸걸.mp3"},
	{name:"퀸씻얼씻얼.gif",							keywords:["씻얼씻얼"],						tags:["퀸","퀸동주"],		soundURL:"Sound/퀸씻얼씻얼.mp3"},
	{name:["퀸빡빡빡01.gif","퀸빡빡빡02.gif"],		keywords:["빡빡빡"],						tags:["퀸","퀸동주"],		soundURL:"Sound/퀸빡빡빡.mp3"},
	{name:"퀸어쩔난퀸임.gif",							keywords:["어쩔난퀸임"],						tags:["퀸","퀸동주"],		soundURL:"Sound/퀸어쩔난퀸임.mp3"},
	{name:"퀸자지러져.gif",							keywords:["자지러져"],						tags:["퀸","퀸동주"],		soundURL:"Sound/퀸자지러져.mp3"},
	{name:"퀸앙딱정.gif",							keywords:["앙딱정"],						tags:["퀸","퀸동주"],		soundURL:"Sound/퀸앙딱정.mp3"},
	{name:"퀸애리얼.gif",							keywords:["애리얼"],						tags:["퀸","퀸동주"],		soundURL:"Sound/퀸애리얼.mp3"},
	{name:"키서내가뽀뽀.gif",						keywords:["내가뽀뽀하는남자찾았어요"],		tags:["보이키서"],		soundURL:"Sound/키서내가뽀뽀하는남자찾았어요.mp3"},
	{name:"키서남키스.gif",							keywords:["남키스"],						tags:["보이키서"],		soundURL:"Sound/키서남키스.mp3"},
	{name:"키서메롱.gif",							keywords:["메롱"],							tags:["보이키서"],		soundURL:"Sound/키서메롱.mp3"},
	{name:"키서빙글빙글돌아가요.gif",				keywords:["빙글빙글돌아가요"],				tags:["보이키서"],		soundURL:"Sound/키서빙글빙글돌아가요.mp3"},
	{name:["/호동콘/정신좀차리라고제발.gif",],				keywords:["정신차려", "정좀제", "정신좀차리라고제발"],		tags:["호동콘"],				soundURL:"Sound/정신좀차리라고제발.wav"},
	{name:["/호동콘/못된생선.gif",],						keywords:["못된생선"],		tags:["호동콘"],				soundURL:"Sound/못된생선.mp3"},
	{name:[
		"/팬아트/popopo_sanae_240414.png",
		"/팬아트/popopo_빟어_241111.png",
		"/팬아트/popopo_사나에_241111.png",
		"/팬아트/도슈_kutaka_240325.jpg",
		"/팬아트/도슈_takane_240408.jpg",
		"/팬아트/란호유_사나에_241101.png",
		"/팬아트/란호유_사나에02_241101.png",
		"/팬아트/레버_sanae_240212.jpg",
	],				keywords:["팬아트", "fanart"],		tags:["팬아트"]},
	{name:["/자작임티/Suwako.gif"],							keywords:["와앙난신님인데"],		tags:["자작임티"]},
	{name:["/자작임티/Marisa.gif"],							keywords:["말랑브이"],				tags:["자작임티"]},
	{name:["/자작임티/Aunn_PopNemoV3.gif"],					keywords:["아운니모"],				tags:["자작임티"]},
	{name:["/자작임티/ReimuSad.png"],						keywords:["렝무절망"],				tags:["자작임티"]},
	{name:["/자작임티/sion.gif"],							keywords:["시온흔들"],				tags:["자작임티"]},
	{name:["/자작임티/Wakasagi_Emoticon_250.gif"],			keywords:["히메으앙"],				tags:["자작임티"]},
	{name:["/자작임티/Ringo_Shake_Original.gif"],			keywords:["링고링"],				tags:["자작임티"]},
	{name:"ㅋ.png",								keywords:["ㅋ"],						tags:["탕탕탕"]},
	{name:"/ETC/그리쑥.png",							keywords:["그리쑥"],						tags:["고양이"],			soundURL:"Sound/ETC/그리쑥.mp3"},
	{name:"/ETC/레아.png",							keywords:["레아"],						tags:["고양이"],			soundURL:"Sound/ETC/레아.mp3"},
	{name:"/ETC/르를뤅키.png",							keywords:["르를뤅키"],						tags:["고양이"],			soundURL:"Sound/ETC/르를뤅키.mp3"},
	{name:"/ETC/좌코비노꽈르띠아노뗄레갈라시에델리빨스파씨오.png",							keywords:["좌코비노꽈르띠아노뗄레갈라시에델리빨스파씨오"],						tags:["고양이"],			soundURL:"Sound/ETC/좌코비노꽈르띠아노뗄레갈라시에델리빨스파씨오.mp3"},
	{name:"/ETC/삠삐.png",							keywords:["삠삐"],						tags:["고양이"],			soundURL:"Sound/ETC/삠삐.mp3"},
	{name:"/ETC/커르피.png",							keywords:["커르피"],						tags:["고양이"],			soundURL:"Sound/ETC/커르피.mp3"},
	{name:"/ETC/릴리.png",							keywords:["릴리"],						tags:["고양이"],			soundURL:"Sound/ETC/릴리.mp3"},
	{name:"/ETC/씨음바.png",							keywords:["씨음바"],						tags:["고양이"],			soundURL:"Sound/ETC/씨음바.mp3"},
	{name:"/ETC/지조레마쥐코가뚜취촐레.png",							keywords:["지조레마쥐코가뚜취촐레"],						tags:["고양이"],			soundURL:"Sound/ETC/지조레마쥐코가뚜취촐레.mp3"},
	{name:"/ETC/루우나.png",							keywords:["루우나"],						tags:["고양이"],			soundURL:"Sound/ETC/루우나.mp3"},
	{name:"/ETC/디나.png",							keywords:["디나"],						tags:["고양이"],			soundURL:"Sound/ETC/디나.mp3"},
	{name:"/ETC/빔바.png",							keywords:["빔바"],						tags:["고양이"],			soundURL:"Sound/ETC/빔바.mp3"},
	{name:"/ETC/페데즈.png",							keywords:["페데즈"],						tags:["고양이"],			soundURL:"Sound/ETC/페데즈.mp3"},
	{name:"/ETC/지스문도엘커스델크캐치매지크루니베르소델아포칼립스.png",							keywords:["지스문도엘커스델크캐치매지크루니베르소델아포칼립스"],						tags:["고양이"],			soundURL:"Sound/ETC/지스문도엘커스델크캐치매지크루니베르소델아포칼립스.mp3"},
	{name:"/ETC/미누.png",							keywords:["미누"],						tags:["고양이"],			soundURL:"Sound/ETC/미누.mp3"},
	{name:[
		"/ETC/팜이01.jpg",
		"/ETC/팜이02.jpg",
		"/ETC/팜이03.jpg",
		"/ETC/팜이04.jpg",
		"/ETC/팜이05.jpg",
		"/ETC/팜이06.jpg",
		"/ETC/팜이07.jpg",
	],							keywords:["팜이"],						tags:["고양이"],			soundURL:"Sound/ETC/팜이.mp3"},
	{name:[
		"/여보야01.gif",
		"/여보야02.gif",
		"/여보야03.gif",
		"/여보야04.gif",
		"/여보야05.gif",
		"/여보야06.gif",
	],							keywords:["여보야"],						tags:["여보야"],
		soundURL:[
			"Sound/여보야01.mp3",
			"Sound/여보야02.mp3",
			"Sound/여보야03.mp3",
			"Sound/여보야04.mp3",
			"Sound/여보야05.mp3",
			"Sound/여보야06.mp3",
	]},
	{name:[
		"/댱끼01.gif",
		"/댱끼02.gif",
		"/댱끼03.gif",
		"/댱끼04.gif",
	],							keywords:["댱끼"],						tags:["명일방주"],
		soundURL:[
			"Sound/댱끼01.mp3",
			"Sound/댱끼02.mp3",
			"Sound/댱끼03.mp3",
	]},
	{name:[
		"/즌다몬/즌다다.gif",
		"이부키.webp",
		"안나.webp",
		"뽀삐.png",
		"/림버스/카론.jpg",
		"/쿠키/밀키.webp",
		"TH/00아큐.png",
		"TH/00코스즈.png",
		"TH/06루미아.png",
		"TH/06대요정.png",
		"TH/06치르노.png",
		"TH/06레미.png",
		"TH/06플랑.png",
		"TH/07첸.png",
		"TH/07릴리.png",
		"TH/08리글.png",
		"TH/09메디슨.png",
		"TH/10스와코.png",
		"TH/11사토리.png",
		"TH/11코이시.png",
		"TH/11키스메.png",
		"TH/12_8루나.png",
		"TH/12_8서니.png",
		"TH/12_8스타.png",
		"TH/13쿄코.png",
		"TH/14신묘마루.png",
		"TH/15클라피.png",
		"TH/16라바.png",	
		"TH/17에이카.png",
	],							keywords:["농"],						tags:["농"]},
	{name:[
		"/즌다몬/즌다다.gif",
		"TH/06대요정.png",
		"TH/06치르노.png",
		"TH/07릴리.png",
		"TH/12_8루나.png",
		"TH/12_8서니.png",
		"TH/12_8스타.png",
		"TH/15클라피.png",
		"TH/16라바.png",	
	],							keywords:["요정"],						tags:["요정"]},
	{name:"안나.webp",							keywords:["안나"],						tags:["파엠블"]},
	{name:"호랑이.jpg",							keywords:["호랑이"],						tags:["호랑이"]},
	{name:"/림버스/카론.jpg",					keywords:["카론"],						tags:["림버스"]},
	{name:"/림버스/으뜸기쁨.png",				keywords:["으뜸기쁨"],						tags:["림버스"]},
	{name:"/림버스/미쳤나보군.png",				keywords:["미쳤나보군"],						tags:["림버스"]},
	{name:"/림버스/장미로쟈.jpg",				keywords:["돈", "돈벌러가자~"],					tags:["림버스"],				soundURL:"Sound/로쟈_돈.mp3"},
	{name:"/림버스/장미로쟈.jpg",				keywords:["야근"],							tags:["림버스"],				soundURL:"Sound/로쟈_야근.mp3"},
	{name:"/림버스/장미로쟈.jpg",				keywords:["누울래"],						tags:["림버스"],				soundURL:"Sound/로쟈_누울래.mp3"},
	{name:"/림버스/으랏챠.gif",				keywords:["으랏~챠!"],						tags:["림버스"],				soundURL:"Sound/돈키_으랏챠.mp3"},
	{name:"/림버스/다람쥐군.webp",				keywords:["다람쥐군!!!!"],						tags:["림버스"],				soundURL:"Sound/다람쥐군.mp3"},
	{name:"/림버스/욥.gif",				keywords:["욥"],						tags:["림버스"],				soundURL:"Sound/욥.mp3"},
	{name:"/림버스/돈키방방.gif",				keywords:["돈키방방"],						tags:["림버스"],				soundURL:"Sound/돈키방방.mp3"},
	{name:"/림버스/아르카나비트.gif",				keywords:["아르카나비트"],						tags:["림버스"],				soundURL:"Sound/아르카나비트.mp3"},
	{name:"/림버스/앤젤라.webp",				keywords:["앤젤라"],						tags:["림버스"],				soundURL:"Sound/앤젤라.mp3"},
	{name:"/림버스/로쟈빙글.gif",				keywords:["로쟈빙글"],						tags:["림버스"],				soundURL:"Sound/로쟈빙글.mp3"},
	{name:"/림버스/로쟈냠냠.gif",				keywords:["로쟈냠냠"],						tags:["림버스"],				soundURL:"Sound/로쟈냠냠.mp3"},
	{name:[
		"신승아.jpg",
		"신승아02.jpg",
		"신승아03.jpg",
		"신승아04.png"
	],							keywords:["승아", "신승아", "승아야"],		tags:["러브딜리버리"],				soundURL:"Sound/승아03.mp3"},
	{name:[
		"신승아.jpg",
		"신승아02.jpg",
		"신승아03.jpg",
		"신승아04.png"
	],							keywords:["승아아저씨"],					tags:["러브딜리버리"],				soundURL:"Sound/승아01.mp3"},
	{name:[
		"신승아.jpg",
		"신승아02.jpg",
		"신승아03.jpg",
		"신승아04.png"
	],							keywords:["승아냄새"],					tags:["러브딜리버리"],						soundURL:"Sound/승아02.mp3"},
	{name:"/쿠키/밀키.webp",						keywords:["밀키"],					tags:["쿠킹덤"],			soundURL:[
		"Sound/Cookie/Milkey/01_특별한차장님이.mp3",
		"Sound/Cookie/Milkey/02_멀쩡한기차줄까.mp3",
		"Sound/Cookie/Milkey/03_꿈속세계는무궁무진해.mp3",
		"Sound/Cookie/Milkey/04_눈을감고은하수를건너는기차를.mp3",
		"Sound/Cookie/Milkey/05_잠든달님은.mp3",
		"Sound/Cookie/Milkey/06_잠시검표시간이있겠습니다.mp3",
		"Sound/Cookie/Milkey/07_달콤한별가루로만들어진멋쟁이차장님등장.mp3",
		"Sound/Cookie/Milkey/08_세상엔별들의꿈으로만들어진.mp3",
		"Sound/Cookie/Milkey/09_오늘도당신의꿈을향해출발.mp3",
		"Sound/Cookie/Milkey/10_뿌뿌승리의기차출발.mp3",
		"Sound/Cookie/Milkey/11_후딱끝내보자구.mp3",
		"Sound/Cookie/Milkey/12_일은해야죠.mp3",
		"Sound/Cookie/Milkey/13_열차가흔들리겠습니다.mp3"
	]},
	{name:"/쿠키/밀키.webp",						keywords:["밀키일해"],					tags:["쿠킹덤"],			soundURL:[
		"Sound/Cookie/Milkey/12_일은해야죠.mp3",
	]},
	{name:"/쿠키/밀키빙글.webp",						keywords:["밀키빙글"],					tags:["쿠킹덤"],			soundURL:[
		"Sound/Cookie/Milkey/13_열차가흔들리겠습니다.mp3"
	]},
	{
		name:"/쿠키/슈크림.webp",						
		keywords:["슈크","슈크림"],					
		tags:["쿠킹덤"],			
		soundURL:[
			"Sound/Cookie/Cream/01_마법이_뭔지.mp3",
			"Sound/Cookie/Cream/02_더이상_실패하지않게.mp3",
			"Sound/Cookie/Cream/03_저는_멋진마법사가.mp3",
			"Sound/Cookie/Cream/04_젤리야_커져라.mp3",
			"Sound/Cookie/Cream/05_실패는_두렵지않아요.mp3",
			"Sound/Cookie/Cream/06_다함께_힘을모으면.mp3",
			"Sound/Cookie/Cream/07_오늘도_보람찬하루를.mp3",
			"Sound/Cookie/Cream/08_제가_또_실수.mp3",
			"Sound/Cookie/Cream/09_사실_책을엄청.mp3",
			"Sound/Cookie/Cream/10_아직_더_할수.mp3",
			"Sound/Cookie/Cream/11_음_뭔가_알것도.mp3",
			"Sound/Cookie/Cream/12_이제_이정도는거뜬.mp3",
			"Sound/Cookie/Cream/13_숙련된_마법사라고요.mp3",
			"Sound/Cookie/Cream/14_어엿한_마법사.mp3",
			"Sound/Cookie/Cream/15_안녕하세요_오답노트.mp3",
			"Sound/Cookie/Cream/16_어려운일이_생기면.mp3",
			"Sound/Cookie/Cream/17_분명_어제_외운건데.mp3",
			"Sound/Cookie/Cream/18_안녕하세요_같이공부.mp3",
			"Sound/Cookie/Cream/19_절_응원.mp3",
			"Sound/Cookie/Cream/20_오늘_연구에_과제.mp3",
			"Sound/Cookie/Cream/21_마법_성공의_조건은.mp3",
			"Sound/Cookie/Cream/22_지치고_힘들때.mp3",
			"Sound/Cookie/Cream/23_이건_비밀인데.mp3",
			"Sound/Cookie/Cream/24_오늘도_보람찬_하루.mp3",
			"Sound/Cookie/Cream/25_당신도_제게.mp3",
			"Sound/Cookie/Cream/26_저도_당신께.mp3",
			"Sound/Cookie/Cream/27_이론공부보다_실전.mp3",
			"Sound/Cookie/Cream/29_고마워요.mp3",
			"Sound/Cookie/Cream/30_예전부터_갖고싶은.mp3",
			"Sound/Cookie/Cream/31_안주셔도_될것.mp3",
			"Sound/Cookie/Cream/32_안녀엉.mp3",
			"Sound/Cookie/Cream/33_또_마법이_제어가.mp3",
			"Sound/Cookie/Cream/34_세상은_책에서_보던것보다.mp3",
			"Sound/Cookie/Cream/35_세상엔_정말_다양한_마법이_많아요.mp3",
			"Sound/Cookie/Cream/36_그뭄달_마법은.mp3",
			"Sound/Cookie/Cream/37_실패가_익숙하다고_항상.mp3",
			"Sound/Cookie/Cream/38_실패가_성공으로.mp3",
			"Sound/Cookie/Cream/39_존경하는_선생님이_있어요.mp3",
		]
	},
	{
		name:"/쿠키/슈크림.webp",						
		keywords:["슈크덕분"],					
		tags:["쿠킹덤"],			
		soundURL:[
			"Sound/Cookie/Cream/19_절_응원.mp3",
		]
	},
	{
		name:"/쿠키/슈크림.webp",						
		keywords:["슈크힘나"],					
		tags:["쿠킹덤"],			
		soundURL:[
			"Sound/Cookie/Cream/22_지치고_힘들때.mp3",
		]
	},
	{
		name:"/쿠키/슈크림.webp",						
		keywords:["슈크당신"],					
		tags:["쿠킹덤"],			
		soundURL:[
			"Sound/Cookie/Cream/25_당신도_제게.mp3",
		]
	},
	{
		name:"/쿠키/슈크림.webp",						
		keywords:["슈크감사"],					
		tags:["쿠킹덤"],			
		soundURL:[
			"Sound/Cookie/Cream/29_고마워요.mp3",
		]
	},
	{
		name:"/쿠키/슈크림.webp",						
		keywords:["슈크괜춘"],					
		tags:["쿠킹덤"],			
		soundURL:[
			"Sound/Cookie/Cream/31_안주셔도_될것.mp3",
		]
	},
	{
		name:"/쿠키/슈크림.webp",						
		keywords:["슈크하이"],					
		tags:["쿠킹덤"],			
		soundURL:[
			"Sound/Cookie/Cream/24_오늘도_보람찬_하루.mp3",
		]
	},
	{
		name:"/쿠키/슈크림.webp",						
		keywords:["슈크바이"],					
		tags:["쿠킹덤"],			
		soundURL:[
			"Sound/Cookie/Cream/32_안녀엉.mp3",
		]
	},
	{name:"/쿠키/망고.webp",						keywords:["망고"],					tags:["쿠킹덤"],			soundURL:[
		"Sound/Cookie/Mango/01_바다건너멋진섬들이.mp3",
	]},
	{name:"/쿠키/펌킨.webp",						keywords:["펌킨"],					tags:["쿠킹덤"],			soundURL:[
		"Sound/Cookie/Pumkin/01_피피도화났대.mp3",
	]},
	{name:"/쿠키/딸크.webp",						keywords:["딸크"],					tags:["쿠킹덤"],			soundURL:[
		"Sound/Cookie/StrawberryCrape/01_와플로봇은단단하고멋있지.mp3",
	]},
	{name:"하치로쿠.jpg",					keywords:["하치로쿠"],				tags:["마이테츠"]},
	{name:"두근두근.gif",					keywords:["두근두근"],				tags:["두근두근"]},
	{name:"역시꼴잘알이노.png",				keywords:["역시꼴잘알이노ㅋㅋ"],				tags:["꼴잘알"]},
	{name:[
		"탕.jpg",
	 	"탕.png"
	],							keywords:["탕"],				tags:["탕"]},
	{name:"포동이.webp",						keywords:["포동이"],					tags:["지자체마스코트"]},
	{name:"뽀삐.png",						keywords:["뽀삐"],					tags:["포켓몬"]},
	{name:"강도에요.png",					keywords:["강도에요"],					tags:["강도"],				soundURL:"Sound/장전.wav"},
	{name:"/동물콘/정말고마워요.gif",				keywords:["정말고마워요"],					tags:["동물콘"]},
	{name:"/동물콘/안아줘요.gif",				keywords:["안아줘요"],					tags:["동물콘"]},
	{name:"/즌다몬/즌다댄스.gif",			keywords:["즌다몬", "즌다댄스"],					tags:["즌다"]},
	{name:"/즌다몬/카르다댄스.gif",			keywords:["카르다몬", "카르다댄스"],					tags:["즌다"]},
	{name:"/즌다몬/앙코댄스.gif",			keywords:["앙코몬", "앙코댄스"],					tags:["즌다"]},
	{name:"/즌다몬/즌다다.gif",				keywords:["즌다다"],					tags:["즌다"]},
	{name:"/즌다몬/즌띠껍댄스.gif",				keywords:["즌띠껍댄스"],					tags:["즌다"]},
	{name:"/즌다몬/모찌모찌즌다.gif",				keywords:["모찌모찌즌다"],					tags:["즌다"]},
	{name:"/즌다몬/즌다즌다쉐이킷.gif",				keywords:["즌다즌다쉐이킷"],					tags:["즌다"]},
	{name:"/즌다몬/즌다!.gif",				keywords:["즌다!", "오키테!"],					tags:["즌다"],				 soundURL:"Sound/zunda_okite.mp3"},
	{name:"/즌다몬/즌다!.gif",				keywords:["아사나노다!"],					tags:["즌다"],						 soundURL:"Sound/zunda_okite.mp3"},
	{name:[
		"/언더테일/sans01.gif",
		"/언더테일/sans02.gif",
		"/언더테일/sans03.gif",
		"/언더테일/sans04.gif",
		"/언더테일/sans05.gif",
		"/언더테일/sans06.gif",
		"/언더테일/sans07.gif",
		"/언더테일/sans08.gif",
		"/언더테일/sans09.gif",
		"/언더테일/sans10.gif",
		"/언더테일/sans11.gif",
		"/언더테일/sans12.gif",
		"/언더테일/sans13.gif",
		"/언더테일/sans14.gif",
		"/언더테일/sans15.gif",
		"/언더테일/sans16.gif",
		"/언더테일/sans17.gif",
		"/언더테일/sans18.gif",
		"/언더테일/sans19.gif",
		"/언더테일/sans20.gif",
		"/언더테일/sans0201.gif",
		"/언더테일/sans0202.gif",
		"/언더테일/sans0203.gif",
		"/언더테일/sans0204.gif",
		"/언더테일/sans0205.gif",
		"/언더테일/sans0206.gif",
		"/언더테일/sans0207.gif",
		"/언더테일/sans0208.gif",
		"/언더테일/sans0301.gif",
		"/언더테일/sans0302.gif",
		"/언더테일/sans0303.gif",
		"/언더테일/sans0304.gif",
		"/언더테일/sans0305.gif",
		"/언더테일/sans0306.gif",
		"/언더테일/sans0401.gif",
		"/언더테일/sans0402.gif",
		"/언더테일/sans0403.gif",
		"/언더테일/sans0404.gif",
		"/언더테일/sans0501.gif",
		"/언더테일/sans0601.gif",
		"/언더테일/sans0701.gif",
		"/언더테일/sans0702.gif",
		"/언더테일/sans0703.gif",
		"/언더테일/sans0801.webp",
		"/언더테일/sans0802.webp",
		"/언더테일/sans0901.gif"],				
		keywords:["샌즈", "sans", "끔찍한시간을보내고싶어?"],					
		tags:["언더테일"],			 
		soundURL:[
			"Sound/Undertale/sans01.mp3",
			"Sound/Undertale/sans02.mp3"
		]
	},
	{name:
		"/언더테일/sanesss.gif",		
		keywords:["싸네스", "sanesss"],					
		tags:["언더테일"],			 
		soundURL:[
			"Sound/Undertale/sanesss.mp3",
		]
	},
	{name:
		"/언더테일/리퍼샌즈.jpg",		
		keywords:["리퍼샌즈"],					
		tags:["언더테일"],			 
		soundURL:[
			"Sound/Undertale/sans01.mp3",
		]
	},
	{name:[
		"/언더테일/papyrusA01.gif",
		"/언더테일/papyrus01.gif",
		"/언더테일/papyrus02.gif",
		"/언더테일/papyrus03.gif",
		],				keywords:["파피루스", "papyrus"],					tags:["언더테일"],			 soundURL:"Sound/Undertale/papyrus.mp3"},
	{name:[
		"/언더테일/asgore0101.gif",
		"/언더테일/asgore0102.gif",
		"/언더테일/asgore0103.gif",
		"/언더테일/asgore0201.webp",
		],				keywords:["아스고어", "asgore"],					tags:["언더테일"],			 soundURL:"Sound/Undertale/asgore.mp3"},	
	{name:[
		"/언더테일/UndyneA01.gif",
		"/언더테일/Undyne01.gif",
		"/언더테일/Undyne02.gif",
		"/언더테일/Undyne03.gif",
		],				keywords:["언다인", "undyne"],					tags:["언더테일"],			 soundURL:"Sound/Undertale/undyne.mp3"},
	{name:[
		"/언더테일/temmiA01.gif",
		"/언더테일/temmi01.gif",
		"/언더테일/temmi02.gif",
		"/언더테일/temmi03.gif",
		"/언더테일/temmi04.gif",
		"/언더테일/temmi05.gif",
		],					keywords:["테미", "temmi"],					tags:["언더테일"],			 soundURL:"Sound/Undertale/temmi.mp3"},
	{name:"/언더테일/bob.jpg",				keywords:["밥", "bob"],					tags:["언더테일"],			 soundURL:"Sound/Undertale/bob.mp3"},
	{name:[
		"/언더테일/alphys0101.gif",
		"/언더테일/alphys0201.gif",
		"/언더테일/alphys0301.gif",
		],				keywords:["알피스", "alphys"],					tags:["언더테일"],			 soundURL:"Sound/Undertale/alphys.mp3"},
	{name:[
		"/언더테일/metatonA01.gif",
		"/언더테일/metaton01.gif",
		"/언더테일/metaton02.gif",
		"/언더테일/metaton03.gif",
		],				keywords:["메타톤", "metaton"],					tags:["언더테일"],			 soundURL:"Sound/Undertale/metaton.mp3"},
	{name:[
		"/언더테일/muffet0101.gif",
		"/언더테일/muffet0102.gif",
		"/언더테일/muffet0103.gif",
		"/언더테일/muffet0201.gif",
		],				keywords:["머펫", "muffet"],					tags:["언더테일"],			 soundURL:"Sound/Undertale/muffet.mp3"},
	{name:[
		"/언더테일/flowey0101.gif",
		"/언더테일/flowey0102.gif",
		"/언더테일/flowey0103.gif",
		"/언더테일/flowey0104.gif",
		"/언더테일/flowey0105.gif",
		"/언더테일/flowey0201.gif",
		"/언더테일/flowey0202.gif",
		"/언더테일/flowey0203.gif",
		"/언더테일/flowey0301.gif",
		],				keywords:["플라위", "flowey"],					tags:["언더테일"],			 soundURL:"Sound/Undertale/flowey.mp3"},
	{name:"/언더테일/asriel.gif",				keywords:["아스리엘", "asriel"],					tags:["언더테일"],			 soundURL:"Sound/Undertale/asriel.mp3"},
	{name:[
		"/언더테일/toriel0101.gif",
		"/언더테일/toriel0102.gif",
		"/언더테일/toriel0103.gif",
		"/언더테일/toriel0104.gif",
		"/언더테일/toriel0105.gif",
		"/언더테일/toriel0201.gif",
		],				keywords:["토리엘", "toriel"],					tags:["언더테일"],			 soundURL:"Sound/Undertale/toriel.mp3"},
	{name:"/언더테일/퉁실이.gif",				keywords:["퉁실이"],						tags:["언더테일"],			 soundURL:"Sound/Undertale/asriel.mp3"},
	{
		name:[
			"/언더테일/metatonEX01.gif",
			"/언더테일/metatonEX02.gif",
			"/언더테일/metatonEX03.gif",
			"/언더테일/metatonEX04.gif",
		],				
		keywords:["메타톤ex", "메타톤EX", "metatonEX", "metatonex"],
		tags:["언더테일"],
		soundURL:[
			"Sound/Undertale/metatonEX01.mp3",
			"Sound/Undertale/metatonEX02.mp3",
			"Sound/Undertale/metatonEX03.mp3",
			"Sound/Undertale/metatonEX04.mp3",
		]
	},
	{name:[
		"/언더테일/napstablook0201.gif",
		"/언더테일/napstablook0101.gif",
		"/언더테일/napstablook0102.gif",
		"/언더테일/napstablook0103.gif",
		],				keywords:["냅스타블룩", "napstablook"],					tags:["언더테일"],			 soundURL:"Sound/Undertale/napstablook.mp3"},
	{name:[
		"/언더테일/chara0101.gif",
		"/언더테일/chara0102.gif",
		"/언더테일/chara0103.gif",
		"/언더테일/chara0104.gif",
		"/언더테일/chara0105.gif",
		"/언더테일/chara0201.gif",
		],				
		keywords:["차라", "chara", "= >", "=>"],		
		tags:["언더테일"]},
	{name:[
		"/언더테일/toriel01.jpeg",
		"/언더테일/toriel02.jpeg",
		"/언더테일/toriel03.jpeg",
		"/언더테일/toriel04.jpeg",
		"/언더테일/toriel05.jpeg",
		"/언더테일/toriel06.jpeg",
		"/언더테일/toriel07.gif",
		"/언더테일/toriel08.gif",
		"/언더테일/toriel09.gif",
		"/언더테일/toriel10.gif"
				],				keywords:["꼴리엘"],					tags:["언더테일"],			 soundURL:"Sound/름피.mp3"},
	{
		name:[
			"/언더테일/HeatFlamesman01.png",
			"/언더테일/HeatFlamesman02.png",
		],				
		keywords:["히트플레임즈맨", "HeatsFlamesman"],		
		tags:["언더테일"]
	},
	{name:"/산나비/마리엉.gif",				keywords:["마리엉"],						tags:["산나비"]},
	{name:"/산나비/마리엉엉.gif",				keywords:["마리엉엉"],						tags:["산나비"]},
	{name:"/산나비/마리으앙.gif",				keywords:["마리으앙"],						tags:["산나비"]},
	{name:"/산나비/마리덜덜.gif",				keywords:["마리덜덜"],						tags:["산나비"]},
	{name:"/산나비/마리바이.gif",				keywords:["마리바이"],						tags:["산나비"]},
	{name:"/산나비/마리반짝.gif",				keywords:["마리반짝"],						tags:["산나비"]},
	{name:"/산나비/마리엣.gif",				keywords:["마리엣"],						tags:["산나비"]},
	{name:"/산나비/마리우웩.gif",				keywords:["마리우웩"],						tags:["산나비"]},
	{name:"/산나비/마리월척.gif",				keywords:["마리월척"],						tags:["산나비"]},
	{name:"/산나비/마리절레.gif",				keywords:["마리절레"],						tags:["산나비"]},
	{name:"/산나비/마리짜잔01.gif",				keywords:["마리짜잔01"],						tags:["산나비"]},
	{name:"/산나비/마리짜잔02.gif",				keywords:["마리짜잔02"],						tags:["산나비"]},
	{name:"/산나비/마리짜잔03.gif",				keywords:["마리짜잔03"],						tags:["산나비"]},
	{name:"/산나비/마리쩐다.gif",				keywords:["마리쩐다"],						tags:["산나비"]},
	{name:"/산나비/마리크하하.gif",				keywords:["마리크하하"],						tags:["산나비"]},
	{name:"/산나비/마리하아.gif",				keywords:["마리하아"],						tags:["산나비"]},
	{name:"/산나비/마리하이.gif",				keywords:["마리하이"],						tags:["산나비"]},
	{name:"/산나비/마리헿.gif",				keywords:["마리헿"],						tags:["산나비"]},
	{name:"/산나비/마리흠.gif",				keywords:["마리흠"],						tags:["산나비"]},
	{name:"/산나비/애기개못해.gif",				keywords:["애기개못해"],						tags:["산나비"]},
	{name:"/산나비/애기그게.gif",				keywords:["애기그게"],						tags:["산나비"]},
	{name:"/산나비/애기동동.gif",				keywords:["애기동동"],						tags:["산나비"]},
	{name:"/산나비/애기두근.gif",				keywords:["애기두근"],						tags:["산나비"]},
	{name:"/산나비/애기뒤적.gif",				keywords:["애기뒤적"],						tags:["산나비"]},
	{name:"/산나비/애기반짝01.gif",				keywords:["애기반짝01"],						tags:["산나비"]},
	{name:"/산나비/애기반짝02.gif",				keywords:["애기반짝02"],						tags:["산나비"]},
	{name:"/산나비/애기브이.gif",				keywords:["애기브이"],						tags:["산나비"]},
	{name:"/산나비/애기생축.gif",				keywords:["애기생축"],						tags:["산나비"]},
	{name:"/산나비/애기신나.gif",				keywords:["애기신나"],						tags:["산나비"]},
	{name:"/산나비/애기싫어.gif",				keywords:["애기싫어"],						tags:["산나비"]},
	{name:"/산나비/애기엣헴.gif",				keywords:["애기엣헴"],						tags:["산나비"]},
	{name:"/산나비/애기위험.gif",				keywords:["애기위험"],						tags:["산나비"]},
	{name:"/산나비/애기윙크.gif",				keywords:["애기윙크"],						tags:["산나비"]},
	{name:"/산나비/애기잘자.gif",				keywords:["애기잘자"],						tags:["산나비"]},
	{name:"/산나비/애기잠깐.gif",				keywords:["애기잠깐"],						tags:["산나비"]},
	{name:"/산나비/애기점프.gif",				keywords:["애기점프"],						tags:["산나비"]},
	{name:"/산나비/애기펄럭.gif",				keywords:["애기펄럭"],						tags:["산나비"]},
	{name:"/산나비/애기행운.gif",				keywords:["애기행운"],						tags:["산나비"]},
	{name:"/산나비/애기호출.gif",				keywords:["애기호출"],						tags:["산나비"]},
	{name:"/산나비/애기흔들.gif",				keywords:["애기흔들"],						tags:["산나비"]},
	{name:"/산나비/야옹이대원이지켜보고있다.gif",				keywords:["야옹이대원이지켜보고있다"],						tags:["산나비"]},
	{name:"/산나비/야옹이대원절레.gif",				keywords:["야옹이대원절레"],						tags:["산나비"]},
	{name:"/산나비/야옹이대원짝짝.gif",				keywords:["야옹이대원짝짝"],						tags:["산나비"]},
	{name:"/산나비/지켜보고있습니다.gif",				keywords:["지켜보고있습니다."],						tags:["산나비"]},
	{name:"/히오스/올피깜놀.png",				keywords:["올피깜놀"],						tags:["히오스"]},
	{name:"/히오스/올피내칭구.png",				keywords:["올피내칭구"],						tags:["히오스"]},
	{name:"/히오스/올피메롱.png",				keywords:["올피메롱"],						tags:["히오스"]},
	{name:"/히오스/올피분노.png",				keywords:["올피분노"],						tags:["히오스"]},
	{name:"/히오스/올피불편.png",				keywords:["올피불편"],						tags:["히오스"]},
	{name:"/히오스/올피뻘쭘.png",				keywords:["올피뻘쭘"],						tags:["히오스"]},
	{name:"/히오스/올피엣헴.png",				keywords:["올피엣헴"],						tags:["히오스"]},
	{name:"/히오스/올피쭈글.png",				keywords:["올피쭈글"],						tags:["히오스"]},
	{name:"/히오스/올피하트.png",				keywords:["올피하트"],						tags:["히오스"]},
	{name:"/히오스/올피하하.png",				keywords:["올피하하"],						tags:["히오스"]},
	{name:"/히오스/올피해피.png",				keywords:["올피해피"],						tags:["히오스"]},
	{name:"헬로.gif",					keywords:["헬로"],				tags:["로보토미"],		soundURL:"Sound/헬로.mp3"},	
	{name:"텐큐사라짐.gif",					keywords:["."],				tags:["동방"]},	
	{name:"현자링고.png",					keywords:["일하기싫어", "일", "월요일"],				tags:["동방"]},
	{name:"난예쁘잖아.png",					keywords:["난예쁘잖아", "공주님"],				tags:["동방"]},
	{name:"퉷.jpg",							keywords:["퉷"],				tags:["동방"]},
	{name:"니하오냥.gif",					keywords:["니하오냥", "냥냥", "냥냥냥냥", "你好娘"],				tags:["동방"],	soundURL:[
		"Sound/니하오냥.mp3",
	]},
	{name:"자렴.png",						keywords:["자렴"],							tags:["동방"]},
	{name:"좋을대로하도록해.png",			keywords:["좋을대로하도록해"],					tags:["동방"]},
	{name:"꿈을꾸고만있네.png",				keywords:["꿈을꾸고만있네"],					tags:["동방"]},
	{name:"죠온.png",						keywords:["죠온","joon"],					tags:["동방"]},
	{name:"죠오프.png",						keywords:["죠오프","jooff"],				tags:["동방"]},
	{name:"아하.png",						keywords:["아하"],							tags:["동방"]},
	{name:"름피.jpg",							keywords:["름피"],						tags:["동방", "름피"],		soundURL:"Sound/름피.mp3"},
	{name:"스님01.png",							keywords:["스님"],						tags:["동방", "스님"]},
	{name:"흥케삐.png",							keywords:["흥케삐"],						tags:["동방"]},
	{name:"사형.gif",							keywords:["사형"],						tags:["동방"]},
	{name:"북둥이.gif",							keywords:["북둥이", "둥둥이"],			tags:["동방"],				soundURL:"Sound/둥둥이.mp3"},
	{name:"둠황챠.gif",							keywords:["둠황챠"],					tags:["동방"]},
	{name:"원망스러워.png",						keywords:["원망스러워"],				tags:["동방"],				soundURL:"Sound/원망스러워.mp3"},
	{name:"찰칵.gif",							keywords:["찰칵"],						tags:["동방"],				soundURL:"Sound/CameraShot1.wav"},
	{name:"푸하하.gif",							keywords:["푸하하"],					tags:["동방"]},
	{name:"레미댄스.gif",						keywords:["레미댄스"],					tags:["동방"]},
	{name:"치르댄스.webp",						keywords:["치르댄스"],					tags:["동방"]},
	{name:"모든걸알아요.gif",					keywords:["모든걸알아요"],				tags:["동방"]},
	{name:"상하.png",						keywords:["상하", "상하이", "상하이!","上海"],			tags:["동방"]},
	{name:"유카하이.gif",						keywords:["유카하이", "유하", "유바"],			tags:["동방"]},
	{name:[
		"유카하이.gif",
	 	"동하01.gif",
	 	"동하02.png",
	 	"동하03.png",
	],						keywords:["동하"],						tags:["동방"]},
	{name:"카센놀람.gif",						keywords:["카센놀람"], 					tags:["동방"]},
	{name:"때려쳐.gif",							keywords:["때려쳐"], 					tags:["동방"]},
	{name:"부들부들.gif",						keywords:["부들부들"], 					tags:["동방"]},
	{name:"치르펀치.gif",						keywords:["치르펀치"], 					tags:["동방"]},
	{name:"몇와똑.gif",							keywords:["몇와똑"], 					tags:["동방"]},
	{name:"유유냠.gif",							keywords:["유유냠"], 					tags:["동방"]},
	{name:"마리흔들.gif",						keywords:["마리흔들"], 					tags:["동방"]},
	{name:"텐시짝짝.gif",						keywords:["텐시짝짝"], 					tags:["동방"],				soundURL:"Sound/텐시짝짝.mp3"},
	{name:"니토짝짝.gif",						keywords:["니토짝짝"], 					tags:["동방"],				soundURL:"Sound/니토짝짝.mp3"},
	{name:"플랑짝짝.gif",						keywords:["플랑짝짝"], 					tags:["동방"],				soundURL:"Sound/플랑짝짝.wav"},
	{name:"레미차한잔.gif",						keywords:["레미차한잔"], 				tags:["동방"],				soundURL:"Sound/레미차한잔.wav"},
	{name:"뚜방쓰담.gif",						keywords:["뚜방쓰담"], 					tags:["동방"]},
	{name:"팔이짧아슬픈요괴.gif",				keywords:["팔이짧아슬픈요괴"], 			tags:["동방"]},
	{name:"요우무사랑해.gif",					keywords:["사랑해"],	 				tags:["동방"]},
	{name:"쟤가.png",							keywords:["쟤가"],	 				tags:["동방"]},
	{name:"웃기지마.png",						keywords:["웃기지마"],	 				tags:["동방"]},
	{name:"없어요.png",							keywords:["없어요"],	 				tags:["동방"]},
	{name:"들켜버렸네요.png",					keywords:["들켜버렸네요"],	 				tags:["동방"]},
	{name:"좋아.png",							keywords:["좋아"],	 				tags:["동방"]},
	{name:"siki01.png",							keywords:["영희부끄"],	 				tags:["동방"]},
	{name:"안된다구.png",						keywords:["안된다구"],	 				tags:["동방"]},
	{name:"모르겠어.png",						keywords:["모르겠어"],	 				tags:["동방"]},
	{name:"하타킥.gif",							keywords:["하타킥"],	 				tags:["동방"],				soundURL:"Sound/하타킥.wav"},
	{name:"감마리.gif",							keywords:["감마리"], 					tags:["동방"]},
	{name:"절레절레.gif",						keywords:["절레절레"], 					tags:["동방"]},
	{name:"TH/10아야.png",						keywords:["걸레걸레"], 					tags:["동방"]},
	{name:"세가냐앙.png",						keywords:["세가냐앙"], 					tags:["동방"]},
	{name:"bwuh.png",						keywords:["bwuh","Bwuh","브워"], 		tags:["동방"]},
	{name:"브워!.png",						keywords:["bwuh!","Bwuh!","브워!"], 	tags:["동방"]},
	{name:"펑.png",							keywords:["자폭", "펑"], 						tags:["동방"]},
	{name:"우위빙글.gif",						keywords:["우위빙글"], 					tags:["동방"]},
	{name:"좌위빙글.gif",						keywords:["좌위빙글"], 					tags:["동방"]},
	{name:"름미댄스.gif",						keywords:["름미댄스","루미댄스","름먀댄스"],				tags:["동방"],		soundURL:"Sound/Yomiyami_BG.mp3"},
	{name:"라바댄스.gif",						keywords:["라바댄스"],				tags:["동방"], 					soundURL:"Sound/Yomiyami_BG.mp3"},
	{name:"방방댄스.gif",						keywords:["방방댄스","방방이"],				tags:["동방"]},
	{name:"메가플레어.gif",						keywords:["메가플레어"],				tags:["동방"], 					soundURL:"Sound/Utsuho_Mega.wav"},
	{name:"우츠간다.gif",						keywords:["우츠간다"],				tags:["동방"], 					soundURL:"Sound/Utsuho_Go.wav"},
	{name:"묭미안.gif",							keywords:["묭미안"],				tags:["동방"], 					soundURL:"Sound/Youmu_Sorry.wav"},
	{name:"단미검.gif",							keywords:["단미검"],				tags:["동방"], 					soundURL:"Sound/Youmu_DanmiSword.wav"},
	{name:"내가벨수없는건.gif",					keywords:["내가벨수없는건"],				tags:["동방"], 					soundURL:"Sound/Youmu_NAI.wav"},
	{name:"사키하하.gif",					keywords:["사키하하"],				tags:["동방"], 					soundURL:"Sound/Kurokoma_Haha.wav"},
	{name:"야치하하.gif",					keywords:["야치하하"],				tags:["동방"], 					soundURL:"Sound/Yachie_Haha.wav"},
	{name:"팔시확대.png",					keywords:["팔시확대"],				tags:["동방"]},
	{name:"따봉마루.png",					keywords:["따봉마루"],				tags:["동방"]},
	{name:[
		"빵ㅋㅋ.gif",
		"TH/모코우/모코우01.gif",
	],							keywords:["빵ㅋㅋ"],				tags:["동방"]},
	{name:"테위겍.gif", 		keywords:["테위겍"], 		tags:["동방"]},
	{name:"/TH/사나에/사나돌댄싱.gif", 		keywords:["사나댄스", "사나돌댄싱"], 		tags:["동방"],			soundURL:"Sound/SanaDollDancing.mp3"},
	{name:[
		"우위빙글.gif",
	 	"좌위빙글.gif",
	], 		keywords:["테위빙글", "테위공중"], 		tags:["동방"]},
	{name:"돈분쿤.png",							keywords:["돈분쿤","돈 분 쿤 !!!","돈분쿤!!!"],	 				tags:["동방"]},
	{name:"우즈댄스.gif",						keywords:["우즈댄스"], 					tags:["동방"]},
	{name:"좌즈댄스.gif",						keywords:["좌즈댄스"], 					tags:["동방"]},
	{name:[
		"좌즈댄스.gif",
	 	"우즈댄스.gif",
	], 		keywords:["나즈댄스"], 		tags:["동방"]},
	{name:"오린댄스01.gif",						keywords:["우린댄스"], 			tags:["동방"]},
	{name:"오린댄스02.gif",						keywords:["좌린댄스"], 			tags:["동방"]},
	{name:[
		"오린댄스01.gif",
	 	"오린댄스02.gif",
	], 		keywords:["오린댄스"], 		tags:["동방"]},
	{name:[
		"/헬테이커/도철댄스.gif",
		"/헬테이커/야치댄스.gif",
		"/헬테이커/사키댄스.gif",
	],		keywords:["헬테이커"], 		tags:["동방"]},
	{name:"/헬테이커/도철댄스.gif",					keywords:["헬도철댄스"], 			tags:["동방"]},
	{name:"/헬테이커/야치댄스.gif",					keywords:["헬야치댄스"], 			tags:["동방"]},
	{name:"/헬테이커/사키댄스.gif",					keywords:["헬사키댄스"], 			tags:["동방"]},
	{name:"/치야댄스.gif",					keywords:["치야댄스"], 			tags:["동방"]},
	{name:"/치야해피댄스.gif",					keywords:["치야해피댄스"], 			tags:["동방"]},
	{name:"바카바카.gif",						keywords:["바카바카"], 				tags:["동방"],				soundURL:"Sound/Cirno_Baka.wav"},
	{name:"Seija01.png",						keywords:["세쟈도발01", "세쟈즐겁"],	 			tags:["동방", "세쟈도발"],				soundURL:"Sound/Seija_Taunt01.wav"},
	{name:"Seija02.png",						keywords:["세쟈도발02", "세쟈담궈"],	 			tags:["동방", "세쟈도발"],				soundURL:"Sound/Seija_Taunt02.wav"},
	{name:"Seija03.png",						keywords:["세쟈도발03", "세쟈할망"],	 			tags:["동방", "세쟈도발"],				soundURL:"Sound/Seija_Taunt03.wav"},
	{name:"Seija04.png",						keywords:["세쟈도발04", "세쟈겨드"],	 			tags:["동방", "세쟈도발"],				soundURL:"Sound/Seija_Taunt04.wav"},
	{name:"Seija05.png",						keywords:["세쟈도발05", "세쟈좋은시절"],	 		tags:["동방", "세쟈도발"],				soundURL:"Sound/Seija_Taunt05.wav"},
	{name:"Seija06.png",						keywords:["세쟈도발06", "세쟈유감"],	 			tags:["동방", "세쟈도발"],				soundURL:"Sound/Seija_Taunt06.wav"},
	{name:"Seija07.png",						keywords:["세쟈도발07", "세쟈느에"],	 			tags:["동방", "세쟈도발"],				soundURL:"Sound/Seija_Taunt07.wav"},
	{name:"Seija08.png",						keywords:["세쟈도발08", "세쟈어이"],	 			tags:["동방", "세쟈도발"],				soundURL:"Sound/Seija_Taunt08.wav"},
	{name:"Seija09.png",						keywords:["세쟈도발09", "세쟈어떻게"],	 			tags:["동방", "세쟈도발"],				soundURL:"Sound/Seija_Taunt09.wav"},
	{name:"Seija10.png",						keywords:["세쟈도발10", "세쟈배신자"],	 			tags:["동방", "세쟈도발"],				soundURL:"Sound/Seija_Taunt10.wav"},
	{name:[
		"/SEXTOY/SEXTOY01.jpg",
	 	"/SEXTOY/SEXTOY02.webp",
		"/SEXTOY/SEXTOY03.jpg",
		"/SEXTOY/SEXTOY04.jpg",
		"/SEXTOY/SEXTOY05.jpg",
		"/SEXTOY/SEXTOY06.jpg",
		"/SEXTOY/SEXTOY07.jpg",
		"/SEXTOY/SEXTOY08.jpg",
		"/SEXTOY/SEXTOY09.png",
		"/SEXTOY/SEXTOY10.gif",
		"/SEXTOY/SEXTOY11.jpg",
		"/SEXTOY/SEXTOY12.png",
		"/SEXTOY/SEXTOY13.png"
	], 		keywords:["SEXTOY", "sextoy"], 		tags:["동방", "TOY"]},
	{name:"빙의화/레센윙크.gif",		keywords:["레센윙크"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/조온어질.gif",		keywords:["조온어질"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/시온내놔.gif",		keywords:["시온내놔"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/첸하이.gif",			keywords:["첸하이"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/유카리하이.gif",		keywords:["유카리하이"], 				tags:["동방", "빙의화"]},
	{name:"빙의화/유카리바이.gif",		keywords:["유카리바이"], 				tags:["동방", "빙의화"]},
	{name:"빙의화/텐시냠.gif",			keywords:["텐시냠"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/카센냠.gif",			keywords:["카센냠"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/카센흥.gif",			keywords:["카센흥"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/카센설교.gif",		keywords:["카센설교"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/도레밍.gif",			keywords:["도레밍"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/렝무댄스.gif",		keywords:["렝무댄스"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/렝무엣헴.gif",		keywords:["렝무엣헴"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/말랑엣헴.gif",		keywords:["말랑엣헴"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/말랑쯧쯧.gif",		keywords:["말랑쯧쯧"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/미코부엉.gif",		keywords:["미코부엉"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/미코폭소.gif",		keywords:["미코폭소"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/슨미등장.gif",		keywords:["슨미등장"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/슨미폭소.gif",		keywords:["슨미폭소"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/신묘달려.gif",		keywords:["신묘달려"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/신묘댄스.gif",		keywords:["신묘댄스"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/코시댄스.gif",		keywords:["코시댄스"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/코시엣헴.gif",		keywords:["코시엣헴"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/후토댄스.gif",		keywords:["후토댄스"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/후토등장.gif",		keywords:["후토등장"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/후토폭소.gif",		keywords:["후토폭소"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/히지가슴.gif",		keywords:["히지가슴"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/히지기도.gif",		keywords:["히지기도"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/히지킥.gif",			keywords:["히지킥"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/히지댄스.gif",		keywords:["히지댄스"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/니토피스.gif",		keywords:["니토피스"], 					tags:["동방", "빙의화"]},
	{name:"빙의화/니토왕피스.gif",		keywords:["니토왕피스"], 				tags:["동방", "빙의화"]},
	{name:"지령기전/프라이버시.png",	keywords:["프라이버시"], 				tags:["동방", "지령기전"]},
	{name:"지령기전/사나분노.png",		keywords:["사나분노"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/사나가슴.png",		keywords:["사나가슴"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/사나띠용.png",		keywords:["사나띠용"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/사나띠용2.png",		keywords:["사나띠용2"], 				tags:["동방", "지령기전"]},
	{name:"지령기전/증거인멸.png",		keywords:["증거인멸"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/히나깜놀.png",		keywords:["히나깜놀"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/아야부끄.png",		keywords:["아야부끄"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/오린빡침.png",		keywords:["오린빡침"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/니토츄.png",		keywords:["니토츄"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/히나츄릅.png",		keywords:["히나츄릅"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/히나엣헴.png",		keywords:["히나엣헴"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/렝무빡침.png",		keywords:["렝무빡침"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/렝무무셔.png",		keywords:["렝무무셔"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/렝무무셔2.png",		keywords:["렝무무셔2"], 				tags:["동방", "지령기전"]},
	{name:"지령기전/스와몰라.png",		keywords:["스와몰라"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/모리야엣헴.png",	keywords:["모리야엣헴"], 				tags:["동방", "지령기전"]},
	{name:"지령기전/구야안농.png",		keywords:["구야안농"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/구야만세.png",		keywords:["구야만세"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/구야폭소.png",		keywords:["구야폭소"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/구야으히.png",		keywords:["구야으히"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/레센으히.png",		keywords:["레센으히"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/레센졸려.png",		keywords:["레센졸려"], 					tags:["동방", "지령기전"]},
	{name:"지령기전/나즈는잘래.jpg",	keywords:["나즈는잘래"], 					tags:["동방", "지령기전"]},
	{name:"스택/하니와01.png",			keywords:["하니와01"], 					tags:["동방", "스택"],				soundURL:"Sound/하니와01.mp3"},
	{name:[
		"FUMO/FUMO1.gif",
		"FUMO/FUMO2.gif",
		"FUMO/FUMO3.gif",
		"FUMO/FUMO4.gif",
		"FUMO/FUMO5.gif",
		"FUMO/FUMO6.gif",
		"FUMO/FUMO7.gif",
		"FUMO/FUMO8.gif",
		"FUMO/FUMO9.gif",
		"FUMO/FUMO10.png",
	],		keywords:["후모", "좆모", "FUMO", "JOTMO", "fumo", "jotmo"], 		tags:["동방", "후모"]},	
	{name:[
		"밍/밍_누에.png",
		"밍/밍_도레미.png",
		"밍/밍_렌코.png",
		"밍/밍_루나사.png",
		"밍/밍_루미아.png",
		"밍/밍_마리사.png",
		"밍/밍_메이링.png",
		"밍/밍_모미지.png",
		"밍/밍_모코우.png",
		"밍/밍_무라사.png",
		"밍/밍_벤벤.png",
		"밍/밍_사구메.png",
		"밍/밍_사나에.png",
		"밍/밍_세이란.png",
		"밍/밍_소악마.png",
		"밍/밍_순호.png",
		"밍/밍_시키.png",
		"밍/밍_오린.png",
		"밍/밍_오키나.png",
		"밍/밍_요우무.png",
		"밍/밍_우동게.png",
		"밍/밍_우츠호.png",
		"밍/밍_유유코.png",
		"밍/밍_유카리.png",
		"밍/밍_치르노.png",
		"밍/밍_카게로.png",
		"밍/밍_케이키.png",
		"밍/밍_코가사.png",
		"밍/밍_코코로.png",
		"밍/밍_쿄코.png",
		"밍/밍_클라피.png",
		"밍/밍_텐시.png",
		"밍/밍_플랑.png",
		"밍/밍_헤카티.png",
		"밍/밍_라이코.png",
		"밍/밍_레미.png",
		"밍/밍_레이무.png",
		"밍/밍_릴리.png",
		"밍/밍_미마.png",
		"밍/밍_사쿠야.png",
		"밍/밍_스미레.png",
		"밍/밍_시즈하.png",
		"밍/밍_아야.png",
		"밍/밍_앨리스.png",
		"밍/밍_코스즈.png",
		"밍/밍_텐큐.png",
		"밍/밍_토지코.png",
		"밍/밍_후토.png",
		"밍/밍_히나.png",
	],		keywords:["밍"], 		tags:["동방", "밍"]},
	{name:[
		"TH/06루미아.png",
	 	"TH/06치르노.png",
	 	"TH/06메이링.png",
	 	"TH/06파츄리.png",
	 	"TH/06사쿠야.png",
	 	"TH/06레미.png",
	 	"TH/06플랑.png",
	 	"TH/06소악마.png",
	 	"TH/06대요정.png",
	],		keywords:["랜동홍마향", "오딸홍마향", "오딸홍마향1", "오딸홍마향2"], 		tags:["동방"]},
	{name:[
		"TH/07레티.png",
	 	"TH/07첸.png",
	 	"TH/07앨리스.png",
	 	"TH/07프리즘리버.png",
	 	"TH/07요우무.png",
	 	"TH/07유유코.png",
	 	"TH/07란.png",
	 	"TH/07유카리.png",
	 	"TH/07릴리.png",
	],		keywords:["랜동요요몽", "오딸요요몽", "오딸요요몽1", "오딸요요몽2"], 		tags:["동방"]},
	{name:[
		"TH/08리글.png",
	 	"TH/08미스티아.png",
	 	"TH/08케이네.png",
	 	"TH/08레이무.png",
	 	"TH/08마리사.png",
		"TH/08테위.png",
	 	"TH/08레이센.png",
	 	"TH/08에이린.png",
	 	"TH/08카구야.png",
	 	"TH/08모코우.png",
	],		keywords:["랜동영야초", "오딸영야초", "오딸영야초1", "오딸영야초2"], 		tags:["동방"]},
	{name:[
		"TH/09메디슨.png",
		"TH/09시키.png",
		"TH/09유카.png",
		"TH/09코마치.png",
	],		keywords:["랜동화영총", "오딸화영총", "오딸화영총1", "오딸화영총2"], 		tags:["동방"]},
	{name:[
		"TH/10니토리.png",
		"TH/10미노리코.png",
		"TH/10히나.png",
		"TH/10아야.png",
		"TH/10사나에.png",
		"TH/10카나코.png",
		"TH/10스와코.png",
		"TH/10시즈하.png",
		"TH/10모미지.png",
	],		keywords:["랜동풍신록", "오딸풍신록", "오딸풍신록1", "오딸풍신록2"], 		tags:["동방"]},
	{name:[
		"TH/11야마메.png",
		"TH/11파르시.png",
		"TH/11유기.png",
		"TH/11사토리.png",
		"TH/11오린.png",
		"TH/11오쿠.png",
		"TH/11코이시.png",
		"TH/11키스메.png",
	],		keywords:["랜동지령전", "오딸지령전", "오딸지령전1", "오딸지령전2"], 		tags:["동방"]},
	{name:[
		"TH/12나즈린.png",
		"TH/12코가사.png",
		"TH/12이치린.png",
		"TH/12무라사.png",
		"TH/12쇼.png",
		"TH/12히지리.png",
		"TH/12누에.png",
	],		keywords:["랜동성련선", "오딸성련선", "오딸성련선1", "오딸성련선2"], 		tags:["동방"]},
	{name:[
		"TH/13쿄코.png",
		"TH/13요시카.png",
		"TH/13청아.png",
		"TH/13후토.png",
		"TH/13미코.png",
		"TH/13마미조.png",
		"TH/13토지코.png",
	],		keywords:["랜동신령묘", "오딸신령묘", "오딸신령묘1", "오딸신령묘2"], 		tags:["동방"]},
	{name:[
		"TH/14히메.png",
		"TH/14세키반키.png",
		"TH/14카게로.png",
		"TH/14벤벤.png",
		"TH/14야츠하시.png",
		"TH/14세이자.png",
		"TH/14신묘마루.png",
		"TH/14라이코.png",
	],		keywords:["랜동휘침성", "오딸휘침성", "오딸휘침성1", "오딸휘침성2"], 		tags:["동방"]},
	{name:[
		"TH/15세이란.png",
		"TH/15링고.png",
		"TH/15도레미.png",
		"TH/15사구메.png",
		"TH/15클라피.png",
		"TH/15순호.png",
		"TH/15헤카티.png",
	],		keywords:["랜동감주전", "오딸감주전", "오딸감주전1", "오딸감주전2"], 		tags:["동방"]},
	{name:[
		"TH/16라바.png",
		"TH/16네무노.png",
		"TH/16아운.png",
		"TH/16나루미.png",
		"TH/16마이.png",
		"TH/16사토노.png",
		"TH/16오키나.png",
	],		keywords:["랜동천공장", "오딸천공장", "오딸천공장1", "오딸천공장2"], 		tags:["동방"]},
	{name:[
		"TH/17에이카.png",
		"TH/17우루미.png",
		"TH/17쿠타카.png",
		"TH/17야치에.png",
		"TH/17마유미.png",
		"TH/17케이키.png",
		"TH/17사키.png",
	],		keywords:["오딸귀형수", "오딸귀형수1", "오딸귀형수2"], 		tags:["동방"]},
	{name:[
		"TH/18미케.png",
		"TH/18타카네.png",
		"TH/18산뇨.png",
		"TH/18미스마루.png",
		"TH/18메구무.png",
		"TH/18텐큐.png",
		"TH/18모모요.png",
		"TH/18츠카사.png",
	],		keywords:["랜동홍룡동", "오딸홍룡동", "오딸홍룡동1", "오딸홍룡동2"], 		tags:["동방"]},
	{name:[
		"TH/19잔무.webp",
		"TH/19손미천.webp",
		"TH/19에노코.webp",
		"TH/19치야리.webp",
		"TH/19히사미.webp"
	],		keywords:["랜동수왕원", "오딸수왕원", "오딸수왕원1", "오딸수왕원2"], 		tags:["동방"]},
	{name:[
		"TH/20우바메.webp",
		"TH/20치미.webp",
		"TH/20나레코.webp",
		"TH/20아사마.webp",
		"TH/20아리야.webp",
		"TH/20니나.webp",
	],		keywords:["랜동금상경", "오딸금상경", "오딸금상경1", "오딸금상경2"], 		tags:["동방"]},
	{name:[
		"TH/07_5스이카.png",
		"TH/12_5하타테.png",
		"TH/10_5이쿠.png",
		"TH/10_5텐시.png",
		"TH/12_8루나.png",
		"TH/12_8서니.png",
		"TH/12_8스타.png",		
		"TH/14_5카센.png",
		"TH/14_5스미레코.png",
		"TH/15_5시온.png",
		"TH/15_5조온.png",
		"TH/17_5도철.png",
		"TH/00레이센.jpg",
		"TH/00린노스케.jpg",
		"TH/00미요이.png",
		"TH/00미즈치.png",
		"TH/00아큐.png",
		"TH/00요리히메.jpg",
		"TH/00토요히메.jpg",
		"TH/00코스즈.png",
	],		keywords:["랜동외전", "오딸외전"], 		tags:["동방"]},
	{name:[
		"TH/00레이센.jpg",
		"TH/00린노스케.jpg",
		"TH/00미요이.png",
		"TH/00미즈치.png",
		"TH/00아큐.png",
		"TH/00요리히메.jpg",
		"TH/00토요히메.jpg",
		"TH/00코스즈.png",
		"TH/01미마.png",
		"TH/06루미아.png",
	 	"TH/06치르노.png",
	 	"TH/06메이링.png",
	 	"TH/06파츄리.png",
	 	"TH/06사쿠야.png",
	 	"TH/06레미.png",
	 	"TH/06플랑.png",
	 	"TH/06소악마.png",
	 	"TH/06대요정.png",
		"TH/07레티.png",
	 	"TH/07첸.png",
	 	"TH/07앨리스.png",
	 	"TH/07프리즘리버.png",
	 	"TH/07요우무.png",
	 	"TH/07유유코.png",
	 	"TH/07란.png",
	 	"TH/07유카리.png",
	 	"TH/07릴리.png",
	 	"TH/07_5스이카.png",
		"TH/08리글.png",
	 	"TH/08미스티아.png",
	 	"TH/08케이네.png",
	 	"TH/08레이무.png",
	 	"TH/08마리사.png",
	 	"TH/08레이센.png",
	 	"TH/08에이린.png",
	 	"TH/08카구야.png",
	 	"TH/08모코우.png",
		"TH/09메디슨.png",
		"TH/09시키.png",
		"TH/09유카.png",
		"TH/09코마치.png",
		"TH/10_5이쿠.png",
		"TH/10_5텐시.png",
		"TH/10니토리.png",
		"TH/10미노리코.png",
		"TH/10히나.png",
		"TH/10아야.png",
		"TH/10사나에.png",
		"TH/10카나코.png",
		"TH/10스와코.png",	
		"TH/10시즈하.png",
		"TH/10모미지.png",	
		"TH/11야마메.png",
		"TH/11파르시.png",
		"TH/11유기.png",
		"TH/11사토리.png",
		"TH/11오린.png",
		"TH/11오쿠.png",
		"TH/11코이시.png",
		"TH/11키스메.png",
		"TH/12나즈린.png",
		"TH/12코가사.png",
		"TH/12이치린.png",
		"TH/12무라사.png",
		"TH/12쇼.png",
		"TH/12히지리.png",
		"TH/12누에.png",
		"TH/12_5하타테.png",
		"TH/12_8루나.png",
		"TH/12_8서니.png",
		"TH/12_8스타.png",
		"TH/13쿄코.png",
		"TH/13요시카.png",
		"TH/13청아.png",
		"TH/13후토.png",
		"TH/13미코.png",
		"TH/13마미조.png",
		"TH/13토지코.png",
		"TH/13_5코코로.png",
		"TH/14히메.png",
		"TH/14세키반키.png",
		"TH/14카게로.png",
		"TH/14벤벤.png",
		"TH/14야츠하시.png",
		"TH/14세이자.png",
		"TH/14신묘마루.png",
		"TH/14라이코.png",
		"TH/14_5카센.png",
		"TH/14_5스미레코.png",
		"TH/15_5시온.png",
		"TH/15_5조온.png",
		"TH/15세이란.png",
		"TH/15링고.png",
		"TH/15도레미.png",
		"TH/15사구메.png",
		"TH/15클라피.png",
		"TH/15순호.png",
		"TH/15헤카티.png",
		"TH/16라바.png",
		"TH/16네무노.png",
		"TH/16아운.png",
		"TH/16나루미.png",
		"TH/16마이.png",
		"TH/16사토노.png",
		"TH/16오키나.png",		
		"TH/17에이카.png",
		"TH/17우루미.png",
		"TH/17쿠타카.png",
		"TH/17야치에.png",
		"TH/17마유미.png",
		"TH/17케이키.png",
		"TH/17사키.png",
		"TH/17_5도철.png",
		"TH/18미케.png",
		"TH/18타카네.png",
		"TH/18산뇨.png",
		"TH/18미스마루.png",
		"TH/18메구무.png",
		"TH/18텐큐.png",
		"TH/18모모요.png",
		"TH/18츠카사.png",
		"TH/19잔무.webp",
		"TH/19손미천.webp",
		"TH/19에노코.webp",
		"TH/19치야리.webp",
		"TH/19히사미.webp",
		"TH/20우바메.webp",
		"TH/20치미.webp",
		"TH/20나레코.webp",
		"TH/20아사마.webp",
		"TH/20아리야.webp",
		"TH/20니나.webp",
	],		keywords:["랜덤동캐", "랜동", "오늘의딸감", "오딸", "오딸1", "오딸2", "오딸3", "오딸4", "오딸5", "오딸6", "오딸7",
						"TodayTouhou", "TT01", "TT02", "TT03", "TT04", "TT05", "TT06", "TT07"], 		tags:["동방"]},
	{name:[
		"TH/마리사/01.png",
		"TH/마리사/02.png",
		"TH/마리사/03.png",
		"TH/마리사/04.png",
		"TH/마리사/05.gif",
		"TH/마리사/06.png",
		"TH/마리사/07.png",
		"TH/마리사/08.jpg",
		"TH/마리사/09.png",
		"TH/마리사/10.png",
		"TH/마리사/11.png",
		"TH/마리사/12.png",
		"TH/마리사/13.png",
		"TH/마리사/14.jpg",
		"TH/마리사/15.png",
		"TH/마리사/16.jpg",
		"TH/마리사/17.png",
		"TH/마리사/18.png",
		"TH/마리사/19.jpg",
		"TH/마리사/20.png",
		"TH/마리사/21.png",
		"TH/마리사/22.png",
		"TH/마리사/23.png",
		"TH/마리사/24.png",
		"TH/마리사/25.jpg",
		"TH/마리사/26.png",
		"TH/마리사/27.png",
		"TH/마리사/28.png",
		"TH/마리사/29.png",
		"TH/마리사/30.png",
	],		keywords:["마리사", "말랑이"], 		tags:["동방"]},
	{name:[
		"TH/도레미/01.png",
		"TH/도레미/02.png",
		"TH/도레미/03.png",
	],		keywords:["도레미"], 		tags:["동방"]},
	{name:[
		"TH/청아/01.png",
		"TH/청아/02.png",
		"TH/청아/03.png",
	],		keywords:["청아"], 		tags:["동방"]},
	{name:[
		"TH/루미아/름미01.gif",
		"TH/루미아/름미02.gif",
		"TH/루미아/름미03.gif",
		"TH/루미아/름미04.gif",
		"TH/루미아/름미05.gif",
		"TH/루미아/름미06.gif",
		"TH/루미아/름미07.gif",
		"TH/루미아/름미08.gif",
		"TH/루미아/름미09.gif",
		"TH/루미아/름미10.gif",
		"TH/루미아/름미11.gif",
		"TH/루미아/름미12.gif",
		"TH/루미아/름미13.gif",
		"TH/루미아/름미14.gif",
		"TH/루미아/름미15.gif",
	],		keywords:["루미아", "름미", "름먀", "누미아"], 		tags:["동방"]},
	{name:[
		"TH/대요정/대요정01.gif",
		"TH/대요정/대요정02.gif",
		"TH/대요정/대요정03.gif",
		"TH/대요정/대요정04.gif",
		"TH/대요정/대요정05.gif",
		"TH/대요정/대요정06.gif",
		"TH/대요정/대요정07.gif",
		"TH/대요정/대요정08.gif",
		"TH/대요정/대요정09.gif",
		"TH/대요정/대요정10.gif",
	],		keywords:["대요정", "다이쟝", "다이쨩"], 		tags:["동방"]},
	{name:[
		"TH/나즈린/01.jpeg",
		"TH/나즈린/02.webp",
		"TH/나즈린/03.jpeg",
		"TH/나즈린/04.jpg",
		"TH/나즈린/05.jpg",
		"TH/나즈린/06.gif",
		"TH/나즈린/07.gif",
	],		keywords:["나즈린"], 		tags:["동방"]},
	{name:[
		"TH/영희누나/01.gif",
		"TH/영희누나/02.gif",
		"TH/영희누나/03.gif",
		"TH/영희누나/04.gif",
		"TH/영희누나/05.gif",
		"TH/영희누나/06.gif",
		"TH/영희누나/07.gif",
	],		keywords:["영희누나", "영희", "시키"], 		tags:["동방"]},
	{name:[
		"TH/요우무/01.gif",
		"TH/요우무/02.gif",
		"TH/요우무/03.gif",
		"TH/요우무/04.gif",
		"TH/요우무/05.gif",
		"TH/요우무/06.gif",
		"TH/요우무/07.gif",
	],		keywords:["요우무", "묭"], 		tags:["동방"],	
	soundURL:[
		"Sound/Youmu_01.wav",
		"Sound/Youmu_02.wav",
		"Sound/Youmu_03.wav",
		"Sound/Youmu_04.wav",
		"Sound/Youmu_05.wav",
		"Sound/Youmu_06.wav",
	]},	
	{name:[
		"TH/코이시/코이시01.gif",
		"TH/코이시/코이시02.gif",
		"TH/코이시/코이시03.gif",
		"TH/코이시/코이시04.gif",
		"TH/코이시/코이시05.gif",
		"TH/코이시/코이시06.gif",
		"TH/코이시/코이시07.gif",
		"TH/코이시/코이시08.gif",
		"TH/코이시/코이시09.gif",
		"TH/코이시/코이시10.gif",
		"TH/코이시/코이시11.gif",
		"TH/코이시/코이시12.gif",
		"TH/코이시/코이시13.gif",
		"TH/코이시/코이시14.gif",
		"TH/코이시/코이시15.gif",
		"TH/코이시/코이시16.gif",
		"TH/코이시/코이시17.gif",
		"TH/코이시/코이시18.gif",
		"TH/코이시/코이시19.gif",
		"TH/코이시/코이시20.gif",
	],		keywords:["코이시", "꺼이싷", "꺼잏", "사랑둥이"], 		tags:["동방"]},
	{name:[
		"TH/코스즈/코스즈01.gif",
		"TH/코스즈/코스즈02.gif",
		"TH/코스즈/코스즈03.gif",
		"TH/코스즈/코스즈04.gif",
		"TH/코스즈/코스즈05.gif",
	],		keywords:["코스즈", "꺼스즈", "내동생"], 		tags:["동방"]},
	{name:[
		"TH/모코우/모코우01.gif",
		"TH/모코우/모코우02.gif",
		"TH/모코우/모코우03.gif",
		"TH/모코우/모코우04.gif",
		"TH/모코우/모코우05.gif",
		"TH/모코우/모코우06.gif",
		"TH/모코우/모코우07.gif",
		"TH/모코우/모코우08.gif",
		"TH/모코우/모코우09.gif",
		"TH/모코우/모코우10.gif",
	],		keywords:["모코우", "모코땅", "모코"], 		tags:["동방"]},	{name:[
		"TH/텐큐/텐큐01.gif",
		"TH/텐큐/텐큐02.gif",
		"TH/텐큐/텐큐03.gif",
		"TH/텐큐/텐큐04.gif",
		"TH/텐큐/텐큐05.gif",
	],		keywords:["텐큐", "뚜방이", "뚜방둥이", "뚜방텐"], 		tags:["동방"]},
	{name:[
		"TH/우츠호/01.gif",
		"TH/우츠호/02.gif",
		"TH/우츠호/03.gif",
		"TH/우츠호/04.gif",
		"TH/우츠호/05.gif",
		"TH/우츠호/06.gif",
		"TH/우츠호/07.gif",
		"TH/우츠호/08.gif",
		"TH/우츠호/09.gif",
		"TH/우츠호/10.gif",
		"TH/우츠호/11.webp",
		"TH/우츠호/12.webp",
	],		keywords:["우츠호", "오쿠"], 		tags:["동방"]},	
];